/*
 * Copyright © 2023 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 *
 *
 * 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
 *		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
 *		Software, provided always that the following conditions are met:
 *		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
 *				or be used in a product, solution or offering which requires the use of another licensed Audinate
 *				product, solution or offering. The Software is not for use as a standalone product without any
 *				reference to Audinate's products;
 *		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
 *				or expectation of performance, compatibility, support, updates or security; and
 *		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
 *				of the Software, and all derivative works of the Software, unless the copies or derivative works are
 *				solely in the form of machine-executable object code generated by the source language processor.
 *
 * 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 *		PURPOSE AND NONINFRINGEMENT.
 *
 * 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
 *		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
 *		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
 *		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
 *		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
 *		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
 *		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
 *		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
 *
 * 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
 *		OR IMPOSE OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
 *		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
 *		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
 *		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF THE
 *		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
 *		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
 *		4.2.	THE REPAIR OF THE SOFTWARE;
 *		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
 *				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
 *
 * 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
 *		the trade names, or product names of Audinate.
 *
 * 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
 *		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
 *		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
 *		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
 *		liability.
 *
 */

/*
 * File : conmon_telemetry.h
 * Created : April 2023
 * Authors : Alan Au
 * Synopsis: ConMon telemetry defintiions
 */

#ifndef _CONMON_TELEMETRY_H
#define _CONMON_TELEMETRY_H

#include <stdint.h>
#include "conmon.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * The type of a single SIGNAL_PRESENCE value
 */
typedef uint8_t conmon_telemetry_signal_presence_t;

/**
 * Get signal presence values, if any, from a ConMon telemetry message
 *
 * @param body Pointer to the message body
 * @param body_len Length in bytes of the message body
 * @param seq_num Pointer to a variable for storing the signal presence payload
 * sequence number. Can be NULL if caller does not want the sequence number returned.
 * @param ntx On input contains the maximum number of TX signal presence values
 * that can be written into the @var tx_signal_presence buffer. On output contains
 * the number of values contained in the payload. This value may be
 * greater than the input value if the number of signal presence values in
 * the payload exceeds the number that can be stored in the TX buffer.
 * @param tx_signal_presence Pointer to buffer for storing the TX signal presence
 * values. If this value is NULL no values will be stored but the @var ntx value will still
 * be set.
 * @param nrx On input contains the maximum number of RX signal presence values
 * that can be written into the @var rx_signal_presence buffer. On output contains
 * the number of values contained in the payload. This value may be
 * greater than the input value if the number of signal presence values in
 * the payload exceeds the number that can be stored in the RX buffer.
 * @param rx_signal_presence Pointer to buffer for storing the RX signal presence
 * values. If this value is NULL no values will be stored but the @var rtx value will still
 * be set.
 * @retval AUD_SUCCESS if msg contains a valid SIGNAL_PRESENCE payload
 * @retval AUD_ERR_NODATA if msg does not contain a SIGNAL_PRESENCE payload
 * @retval An AUD_ERR value on any other error
 */
aud_error_t
conmon_telemetry_msg_get_signal_presence
(
	const conmon_message_body_t * body,
	uint16_t body_len,
	uint16_t * seq_num,
	uint16_t * ntx,
	conmon_telemetry_signal_presence_t * tx_signal_presence,
	uint16_t * nrx,
	conmon_telemetry_signal_presence_t * rx_signal_presence
);

#ifdef __cplusplus
}
#endif

#endif // CONMON_TELEMETRY_H

/*
 * Copyright © 2023 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 */
