/*
 * File      : dante_api_version.h
 * Timestamp : 2025-03-18 06:30:49
 * Author    : James Westendorp
 * Synopsis  : Dante API versions header file
 *
 * Copyright 2022 Audinate Pty Ltd and/or its licensors
 * 
 *
 * NOTE:
 * This file is automatically generated during the build from the following environment variables:
 * DAPI_VERSION_<XXXX> where XXXX is MAJOR, MINOR, BUGFIX
 * 
 * Those strings cannot be directly included in this comment due to the usage of the 
 * build_win/extract_version_c.sh on windows which tries to extract the versions from 
 * the first instance it finds of the VERSION_<XXXX> substrings.
 *
 */

#ifndef _DANTE_API_VERSION_H
#define _DANTE_API_VERSION_H

/** The major version number for the overall Dante API */
#define DANTE_API_VERSION_MAJOR  4

/** The minor version number for the overall Dante API */
#define DANTE_API_VERSION_MINOR  9

/** The bugfix version number for the overall Dante API */
#define DANTE_API_VERSION_BUGFIX 1

/**
 * Version number as binary uint32.
 *
 * XX - major version
 * XX - minor version
 * XXXX - bugfix version
 */
#define DANTE_API_VERSION_PACKED ((DANTE_API_VERSION_MAJOR <<24) | (DANTE_API_VERSION_MINOR << 16) | DANTE_API_VERSION_BUGFIX)

#endif

