/*
 * Copyright © 2007-2025 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 *
 *
 * 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
 *		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
 *		Software, provided always that the following conditions are met:
 *		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
 *				or be used in a product, solution or offering which requires the use of another licensed Audinate
 *				product, solution or offering. The Software is not for use as a standalone product without any
 *				reference to Audinate's products;
 *		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
 *				or expectation of performance, compatibility, support, updates or security; and
 *		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
 *				of the Software, and all derivative works of the Software, unless the copies or derivative works are
 *				solely in the form of machine-executable object code generated by the source language processor.
 *
 * 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 *		PURPOSE AND NONINFRINGEMENT.
 *
 * 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
 *		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
 *		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
 *		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
 *		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
 *		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
 *		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
 *		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
 *
 * 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
 *		OR IMPOSES OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
 *		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
 *		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
 *		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF
 *		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
 *		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
 *		4.2.	THE REPAIR OF THE SOFTWARE;
 *		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
 *				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
 *
 * 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
 *		the trade names, or product names of Audinate.
 *
 * 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
 *		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
 *		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
 *		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
 *		liability.
 *
 */

/*
 * File     : platform_types.h
 * Created  : March 2007
 * Author   : James Westendorp
 * Synopsis : Basic types in the API
 */
/**
 * @file platform_types.h
 *
 * Standard cross-platform type definitions used throughout the Dante API.
 *
 * Do not include this file directly, instead include "audinate/dante_api.h"
 */
#ifndef _AUD_PLATFORM_TYPES_H
#define _AUD_PLATFORM_TYPES_H

#ifndef AUD_PLATFORM
#error platform_types.h should never be included directly
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** A cross-platform boolean type definition */
typedef unsigned int aud_bool_t;

/** A cross-platform definition for FALSE */
#define AUD_FALSE 0

/** A cross-platform definition for TRUE */
#define AUD_TRUE 1

#ifndef NO
/** A synonym for AUD_FALSE */
#define NO AUD_FALSE
#endif

#ifndef YES
/** A synonym for AUD_TRUE */
#define YES AUD_TRUE
#endif

#ifndef INT32_MAX
/** The maximum possible value for a signed 32-bit value */
#define INT32_MAX 0xFFFFFFFF
#endif

#ifndef UINT32_MAX
/** The maximum possible value for an unsigned 32-bit value */
#define UINT32_MAX 0xFFFFFFFF
#endif

/**
 * Mark unused parameter in functions, useful for removing compiler warnings
 * when parameters are known to be not needed.
 */
#ifndef AUD_UNUSED
#define AUD_UNUSED(PARAM) (void) PARAM;
#endif


// Define common MAX and MIN macros if not already defined.

#ifndef MAX
/** Define MAX if we don't already have it */
#define MAX(x,y) (((x) >= (y)) ? (x) : (y))
#endif

#ifndef MIN
/** Define MIN if we don't already have it */
#define MIN(x,y) (((x) <= (y)) ? (x) : (y))
#endif

//----------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif

/*
 * Copyright © 2007-2025 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 */
