/*
 * Copyright © 2007-2025 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 *
 *
 * 1.	Subject to the terms and conditions of this Licence, Audinate hereby grants you a worldwide, non-exclusive,
 *		no-charge, royalty free licence to copy, modify, merge, publish, redistribute, sublicense, and/or sell the
 *		Software, provided always that the following conditions are met:
 *		1.1.	the Software must accompany, or be incorporated in a licensed Audinate product, solution or offering
 *				or be used in a product, solution or offering which requires the use of another licensed Audinate
 *				product, solution or offering. The Software is not for use as a standalone product without any
 *				reference to Audinate's products;
 *		1.2.	the Software is provided as part of example code and as guidance material only without any warranty
 *				or expectation of performance, compatibility, support, updates or security; and
 *		1.3.	the above copyright notice and this License must be included in all copies or substantial portions
 *				of the Software, and all derivative works of the Software, unless the copies or derivative works are
 *				solely in the form of machine-executable object code generated by the source language processor.
 *
 * 2.	TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 *		EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
 *		PURPOSE AND NONINFRINGEMENT.
 *
 * 3.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL AUDINATE BE LIABLE ON ANY LEGAL THEORY
 *		(INCLUDING, WITHOUT LIMITATION, IN AN ACTION FOR BREACH OF CONTRACT, NEGLIGENCE OR OTHERWISE) FOR ANY CLAIM,
 *		LOSS, DAMAGES OR OTHER LIABILITY HOWSOEVER INCURRED.  WITHOUT LIMITING THE SCOPE OF THE PREVIOUS SENTENCE THE
 *		EXCLUSION OF LIABILITY SHALL INCLUDE: LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR CORRUPTION OF
 *		DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS, OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC
 *		LOSS; OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, ARISING OUT OF OR
 *		IN CONNECTION WITH THIS AGREEMENT, ACCESS OF THE SOFTWARE OR ANY OTHER DEALINGS WITH THE SOFTWARE, EVEN IF
 *		AUDINATE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH CLAIM, LOSS, DAMAGES OR OTHER LIABILITY.
 *
 * 4.	APPLICABLE LEGISLATION SUCH AS THE AUSTRALIAN CONSUMER LAW MAY APPLY REPRESENTATIONS, WARRANTIES, OR CONDITIONS,
 *		OR IMPOSES OBLIGATIONS OR LIABILITY ON AUDINATE THAT CANNOT BE EXCLUDED, RESTRICTED OR MODIFIED TO THE FULL
 *		EXTENT SET OUT IN THE EXPRESS TERMS OF THIS CLAUSE ABOVE "CONSUMER GUARANTEES".	 TO THE EXTENT THAT SUCH CONSUMER
 *		GUARANTEES CONTINUE TO APPLY, THEN TO THE FULL EXTENT PERMITTED BY THE APPLICABLE LEGISLATION, THE LIABILITY OF
 *		AUDINATE UNDER THE RELEVANT CONSUMER GUARANTEE IS LIMITED (WHERE PERMITTED AT AUDINATE'S OPTION) TO ONE OF
 *		FOLLOWING REMEDIES OR SUBSTANTIALLY EQUIVALENT REMEDIES:
 *		4.1.	THE REPLACEMENT OF THE SOFTWARE, THE SUPPLY OF EQUIVALENT SOFTWARE, OR SUPPLYING RELEVANT SERVICES AGAIN;
 *		4.2.	THE REPAIR OF THE SOFTWARE;
 *		4.3.	THE PAYMENT OF THE COST OF REPLACING THE SOFTWARE, OF ACQUIRING EQUIVALENT SOFTWARE, HAVING THE RELEVANT
 *				SERVICES SUPPLIED AGAIN, OR HAVING THE SOFTWARE REPAIRED.
 *
 * 5.	This License does not grant any permissions or rights to use the trade marks (whether registered or unregistered),
 *		the trade names, or product names of Audinate.
 *
 * 6.	If you choose to redistribute or sell the Software you may elect to offer support, maintenance, warranties,
 *		indemnities or other liability obligations or rights consistent with this License. However, you may only act on
 *		your own behalf and must not bind Audinate. You agree to indemnify and hold harmless Audinate, and its affiliates
 *		from any liability claimed or incurred by reason of your offering or accepting any additional warranty or additional
 *		liability.
 *
 */

/*
 * File     : platform_error.h
 * Created  : March 2007
 * Author   : James Westendorp
 * Synopsis : Error codes for the Audinate Cross-Platform API
 */
/**
 * @file platform_error.h
 *
 * Cross-platform error types and definitions used by the Dante API
 *
 * Do not include this file directly, instead include "audinate/dante_api.h"
 */
#ifndef _AUD_PLATFORM_ERROR_H
#define _AUD_PLATFORM_ERROR_H

#ifndef AUD_PLATFORM
#error platform_error.h must not be included directly.
#endif

#ifdef __cplusplus
extern "C" {
#endif


//----------------------------------------------------------
// Error types
//----------------------------------------------------------

/**
 * typedef for an Audinate error code
 */
typedef unsigned int aud_error_t;

/**
 * typedef for a system error code
 */
typedef unsigned int aud_system_error_t;

/**
 * A string buffer used for printing human-readable error strings
 */
typedef char aud_errbuf_t[AUD_ENV_ERROR_STRLEN+1];

/**
 * Create an error message for the given error. The string format
 * will be:
 * For non-system errors, a message of the form:
 *   "<description>(<code>)"
 * For AUD_ERR_SYSTEM, a message of the form:
 *   "system error: <description>(<code>)"
 * based on the last system error.
 *
 * @param error the error code 
 * @param errbuf the buffer to contain the printed error message
 *
 * @return errbuf
 */
const char *
aud_error_message
(
	aud_error_t error,
	aud_errbuf_t errbuf
);

//----------
// More specific error functions below here
//----------

/**
 * convert a system error info an audinate API error
 *
 * @param error the system error to be converted to a Dante platform error
 *
 * @return the aud_error_t representation of the given system error
 */
aud_error_t
aud_error_from_system_error
(
	aud_system_error_t error
);

/**
 * Get the last system error
 *
 * @return the last system error 
 */
aud_system_error_t
aud_system_error_get_last (void);

/**
 * Convert the last system error into an API error if possible.
 * This is a convenience method that uses the other functions
 *
 * @return the last system error converted to an aud_error_t
 */
AUD_INLINE aud_error_t
aud_error_get_last (void)
{
	return aud_error_from_system_error(aud_system_error_get_last());
}

/**
 * Get the name of the error code as a string
 * returns NULL if not a valid error
 *
 * @param error the error code
 * 
 * @return a string with the name of the given error 
 */
const char *
aud_error_get_name
(
	aud_error_t error
);

/**
 * Get the description of the error code
 * returns NULL if not a valid error
 *
 * @param error the error code
 *
 * @return a string with a description of the given error
 */
const char *
aud_error_get_description
(
	aud_error_t error
);

/**
 * Get a string description of the last system error.
 * This method should always return a string of some sort
 * even if the error code is unknown
 *
 * @param error the system error code
 *
 * @return a string with a description of the given system error
 */
const char *
aud_system_error_get_description
(
	aud_system_error_t error
);


//----------------------------------------------------------
// generic errors
//----------------------------------------------------------

// This list is replicated in sw__controller/util/src/com/audinate/IAudinateConstants.java
// If you make any changes to this list, you need to make matching changes there to maintain DC.

enum {
	AUD_SUCCESS,              // no error, all good
	AUD_ERR_DONE,             // operation done (eg EOF)
						      //  Use this to halt loops or similar where 'success'
							  //  means "all good, keep going'.
	AUD_ERR_SYSTEM,           // error was a system error not handled by API
	AUD_ERR_INVALIDPARAMETER, // invalid function parameter
	AUD_ERR_INVALIDDATA,      // internal data is incompatible with function
	AUD_ERR_INVALIDSTATE,     // wrong state to perform action
	AUD_ERR_NOMEMORY,         // out of memory
	AUD_ERR_INTERRUPTED,      // the operation was interrupted
	AUD_ERR_TRUNCATED,        // data truncation occured 
	AUD_ERR_NOTSUPPORTED,     // the operation is not supported on this platform
	AUD_ERR_TIMEDOUT,         // a time-restricted operation timed out
	AUD_ERR_NOTFOUND,         // a value was searched for but not found,
                              // e.g. in event_loop_socket_event_update
	AUD_ERR_DNSSDFAIL,        // DNS-SD failed
	AUD_ERR_RANGE,            // data out of range
	AUD_ERR_POLICY,           // administrative policy violation
	AUD_ERR_VERSION,          // version mismatch
	AUD_ERR_CANCELLED,        // operation is cancelled
	AUD_ERR_CLOSING,          // operation is cancelled because underlying resource is closing / disconnecting

	// Socket Errors, Mainly BSD-style mappings from E<ERR> to AUD_ERR_<ERR>
	// commented out values are codes which have not yet been required
	// or can be mapped to other settings
	AUD_ERR_ACCES,
	AUD_ERR_ADDRINUSE,
	AUD_ERR_ADDRNOTAVAIL,
	AUD_ERR_AFNOSUPPORT,
	// AUD_ERR_AGAIN,       // map to AUD_ERR_TIMEDOUT
	AUD_ERR_ALREADY,
	AUD_ERR_BADF,
	AUD_ERR_CONNABORTED,
	AUD_ERR_CONNREFUSED,
	AUD_ERR_CONNRESET,
	AUD_ERR_DESTADDRREQ,
	AUD_ERR_FAULT,
	AUD_ERR_HOSTUNREACH,
	// AUD_ERR_HOST_NOT_FOUND,
	AUD_ERR_INPROGRESS,
	//AUD_ERR_INTR,          // <- map to AUD_ERR_INTERRUPTED
	// AUD_ERR_INVAL,        // <- map to AUD_ERR_INVALIDPARAMETER
	//AUD_ERR_IO,
	AUD_ERR_ISCONN,
	AUD_ERR_MFILE,
	AUD_ERR_MSGSIZE,
	AUD_ERR_NETDOWN,
	AUD_ERR_NETRESET,
	AUD_ERR_NETUNREACH,
	// AUD_ERR_NFILE,
	// AUD_ERR_NOADDRESS,
	AUD_ERR_NOBUFS,
	AUD_ERR_NODATA,
	AUD_ERR_NODEV,
	// AUD_ERR_NOMEM,      // <- map to AUD_ERR_NOMEMORY
	AUD_ERR_NOPROTOOPT,
	AUD_ERR_NORECOVERY,
	// AUD_ERR_NOSUPPORT,
	AUD_ERR_NOTCONN,
	AUD_ERR_NOTINITIALISED,
	AUD_ERR_NOTSOCK,
	//AUD_ERR_OPNOTSUPP, // <- map to AUD_ERR_NOTSUPPORTED
	// AUD_ERR_PERM,
	//AUD_ERR_PIPE,
	AUD_ERR_PROTONOSUPPORT,
	AUD_ERR_PROTOTYPE,
	AUD_ERR_SHUTDOWN,
	AUD_ERR_SOCKTNOSUPPORT,
	//AUD_ERR_TIMEDOUT,  // <- map to AUD_ERR_TIMEDOUT
	AUD_ERR_TRYAGAIN,
	//AUD_ERR_WOULDBLOCK, // <- map to AUD_ERR_TIMEDOUT

	AUD_ERR_NOTRUNNING,

	AUD_ERR_BANDWIDTH_EXCEEDED, // A call failed due to bandwidth limitations (eg. flow creation in the APE)

	// useful to indicate transitional state in multi-stage operations
	AUD_ERR_NOT_READY,

	AUD_ERR_DATATOOLONG, // Maps from system error ENAMETOOLONG. Data or a filename was too long, and the system call failed.

	// useful for iterating through all known error codes
	AUD_NUM_ERRORS
};

// The above list is replicated in sw__controller/util/src/com/audinate/IAudinateConstants.java
// If you make any changes to this list, you need to make matching changes there to maintain DC.

#ifdef __cplusplus
}
#endif

#endif

/*
 * Copyright © 2007-2025 Audinate Pty Ltd ACN 120 828 006 (Audinate). All rights reserved.
 */

